# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kcCa198GYSfQEq2fVVYhwr-gkvoqw5JO

1.	En Python, crea una variable por cada letra de tu nombre y asigna a la variable la letra de tu nombre que corresponde y que luego imprima en pantalla cada letra del nombre y finalmente el nombre entero:

Output: P e d r o
  Pedro
"""

D = 'D'
a = 'a'
i = 'i'
r = 'r'
o = 'o'
print(D, a, i, r, o) 
print(D+a+i+r+o)

"""2.	Escribe un programa en Python que pregunte el nombre del usuario, su edad y su correo electrónico y que luego imprima el siguiente mensaje en pantalla:

Input: Digite su nombre: Pedro
	Digite su edad: 30
	Digite su correo electrónico: p3dr1t0_12345@gmail.com
Output: Bienvenido al sistema Pedro, su correo electrónico es p3dr1t0_12345@gmail.com y tiene 30 años de edad
  
"""

nombre = input('Digite su nombre: ')
edad = input('Digite su edad: ')
correo = input('Digite su correo electrónico: ')
print('Bienvenido al sistema ',nombre,', su correo electrónico es ', correo, ' y tiene ',edad, ' años de edad', sep='')

"""
	Utilizando Python, dado un número n calcula la siguiente operación: ((n^2+2n)/2) e imprime en pantalla el resultado:

Output: El resultado de la operación es
"""

numero = int(input('Inrese el número: '))
resultado = ((numero^2+2*numero)/2)

print('El resultado de la operación es:', resultado)

"""	Escribe un programa que convierta grados Celsius a grados Fahrenheit sabiendo que (0° C×9/5)+32= 32 °F y luegoa imprima en pantalla el resultado:

Input: Grados Celsius
Output: Grados Fahrenheit

"""

grados = int(input('Ingrese los grados: '))
resultado = (grados * 9 /5)+32
print(resultado)

"""5.	Escribe un programa que pregunte por las horas trabajadas en el día y luego calcule el valor de su salario en ese día sabiendo que el costo de la hora de trabajo es de 7.500 $:"""

horas_trabajadas = int(input('¿Cuántas horas trabajó hoy?  '))
resultado = horas_trabajadas * 7500
print('Su salario el día de hoy es de ',resultado,'$')

"""6.	Escribe un programa que imprima en pantalla el largo de una cadena de texto:

Input: Ingrese una cadena de texto: ¡Hola mundo!
Output: La cadena de texto tiene 12 caracteres

"""

cadena = input(' Ingrese una cadena de texto: ')
print(len(cadena))

"""7.	En Python, asigna a las variables v y f los datos booleanos True y False respectivamente y luego imprime en pantalla las siguientes comparaciones:

-v or f

-v and f

-not v

-not f

Saca tus propias conclusiones sobre los resultados mostrados.

"""

v = True
f = False
print(v or f)
print(v and f)
print(not v)
print(not f)

Dairo Arley García Vergara  --> Envia el correo
dairo.garcia@udea.edu.co
cc 1037974366